---
- name: Unsubscribe
  hosts: all
  become: true
  become_user: root
  become_method: ansible.builtin.sudo

  tasks:
    - name: Create end of subscription file
      ansible.builtin.file:
        path: "/etc/{{ now(utc=true, fmt='%Y%m%d_%Hh%Mm%Ss') }}_unsubscribed.txt"
        state: touch
        mode: '0644'
